[package]
distribution = "2201.11.0"
org = "ballerina"
name = "wsdltool"
version = "1.0.2"
authors = ["Ballerina"]
keywords = ["wsdl"]
repository = "https://github.com/ballerina-platform/wsdl-tools"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = false

[[platform.java21.dependency]]
groupId = "io.ballerina"
artifactId = "xsd-core"
version = "1.0.6"
path = "lib/xsd-core-1.0.6.jar"
