[tool]
id = "wsdl"

[[dependency]]
path = "../wsdl-cli/build/libs/wsdl-cli-1.2.0-SNAPSHOT.jar"

[[dependency]]
path = "../wsdl-core/build/libs/wsdl-core-1.2.0-SNAPSHOT.jar"

[[dependency]]
path = "lib/xsd-core-1.1.2.jar"

[[dependency]]
path = "lib/wsdl4j-1.6.3.jar"

[[dependency]]
path = "lib/XmlSchema-1.4.7.jar"
